name: Setup Rust
description: Set up and caching for Rust builds

inputs:
  build-type:
    description: The build type that will be performed. E.g. debug or clippy.
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Cache target
      uses: actions/cache@v3
      with:
        path: target
        key: rust-${{ runner.os }}-${{ hashfiles('Cargo.lock') }}-${{ inputs.build-type }}-${{ github.sha }}
        restore-keys: |
          rust-${{ runner.os }}-${{ hashfiles('Cargo.lock') }}-${{ inputs.build-type }}-
          rust-${{ runner.os }}-${{ hashfiles('Cargo.lock') }}-
          rust-${{ runner.os }}-

