[package]
name = "recipes"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
axum = "0.6.18"
serde = { version = "1.0.163", features = ["derive"] }
sqlx = { version = "0.6", features = ["runtime-tokio-native-tls", "sqlite"] }
tokio = { version = "1.28.1", features = ["macros", "rt-multi-thread"] }
