#!/bin/sh

reset="$(printf '\033[0m')"
red="$(printf '\033[31m')"
green="$(printf '\033[32m')"

fail_at_step() {
  printf '\n%s: %sFAILED%s\n' "$1" "$red" "$reset"
  exit 1
}

# Make sure the program can be compiled
cargo check || fail_at_step 'Compile'

# Make sure the code is formatted correctly
cargo fmt --check --all || fail_at_step 'Formatting'

# Lint the code
cargo clippy --verbose -- -D warnings -D clippy::pedantic -D clippy::cargo -A \
  clippy::module-name-repetitions -A clippy::multiple_crate_versions || \
  fail_at_step 'Clippy'

# Test the code
cargo test --workspace || fail_at_step 'Tests'


printf '\nAll checks %spassed%s\n' "$green" "$reset"
