name: Rust CI

on:
  push:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
    - name: Build
      run: cargo build --verbose
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
    - name: Build
      run: cargo build --verbose --release
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
    - name: Check format
      run: cargo fmt --check --all --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings
