name: Rust CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
      with:
        build-type: debug
        toolchain-profile: minimal
    - name: Build
      run: cargo build --verbose
  build-release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
      with:
        build-type: release
        toolchain-profile: minimal
    - name: Build
      run: cargo build --verbose --release
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
      with:
        build-type: format
        toolchain-component: rustfmt
    - name: Check format
      run: cargo fmt --check --all --verbose
  clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
      with:
        build-type: clippy
        toolchain-component: clippy
    - name: Run Clippy
      run: cargo clippy --verbose -- -D warnings
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v3
    - name: Setup
      uses: ./.github/actions/setup-rust
      with:
        build-type: debug
        toolchain-profile: minimal
    - name: Run unit tests
      run: cargo test --workspace
